name: Sync LLM models to Supabase

on:
  push:
    # only trigger when your JSON changes
    branches:
      - main
    paths:
      - model_pricing.json

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]

    # pick up two sets of secrets (SUPABASE_STAGING_* and SUPABASE_PRODUCTION_*)
    env:
      SUPABASE_URL: ${{ secrets['SUPABASE_' + matrix.env.toUpperCase() + '_URL'] }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets['SUPABASE_' + matrix.env.toUpperCase() + '_SERVICE_ROLE_KEY'] }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase

      - name: Run sync script
        run: |
          python scripts/sync_models.py \
            --json path/to/models.json \
            --schema prisma/schema.prisma \
            --env ${{ matrix.env }}
