name: Sync LLM models to Supabase

on:
  push:
    branches:
      - development
      - main
    paths:
      - model_pricing.json

  workflow_dispatch:
    inputs:
      env:
        description: 'Which environment to sync?'
        required: true
        default: 'staging'

jobs:
  sync-staging:
    # Run on development pushes, or on any manual dispatch (so that needs: is satisfied)
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/development')
      || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: staging
    env:
      SUPABASE_URL:               ${{ secrets.SUPABASE_STAGING_URL }}
      SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_STAGING_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Validate JSON
        run: python -m json.tool model_pricing.json
      - name: Install dependencies
        run: pip install supabase

      - name: Sync to staging
        if: >
          (github.event_name == 'push' && github.ref == 'refs/heads/development')
          || (github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'staging')
        run: |
          python scripts/sync_models.py \
            --json model_pricing.json \
            --env staging

  sync-production:
    needs: sync-staging
    # Trigger on main pushes or manual dispatch with env=production
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
      || (github.event_name == 'workflow_dispatch' && github.event.inputs.env == 'production')
    runs-on: ubuntu-latest
    environment: production
    env:
      SUPABASE_URL:               ${{ secrets.SUPABASE_PRODUCTION_URL }}
      SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_PRODUCTION_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Validate JSON
        run: python -m json.tool model_pricing.json
      - name: Install dependencies
        run: pip install supabase
      - name: Sync to production
        run: |
          python scripts/sync_models.py \
            --json model_pricing.json \
            --env production