name: Sync LLM models to Supabase

on:
  push:
    branches:
      - develop
      - main
    paths:
      - model_pricing.json
    workflow_dispatch:

jobs:
  sync-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: staging
    env:
      SUPABASE_URL:               ${{ secrets.SUPABASE_STAGING_URL }}
      SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_STAGING_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install supabase

      - name: Sync to staging
        run: python scripts/sync_models.py \
               --json model_pricing.json \
               --env staging

  sync-production:
    if: github.ref == 'refs/heads/main'
    needs: sync-staging
    runs-on: ubuntu-latest
    environment: production
    env:
      SUPABASE_URL:               ${{ secrets.SUPABASE_PRODUCTION_URL }}
      SUPABASE_SERVICE_ROLE_KEY:  ${{ secrets.SUPABASE_PRODUCTION_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install supabase

      - name: Sync to production
        run: python scripts/sync_models.py \
               --json model_pricing.json \
               --env production
